### ISSUE TITLE
Package CsdlToDiagram 0.14.1 is not compatible with net5.0 for vs2019

### ISSUE THREAD

**Issue by caigen** [garethj-msft/CsdlToDiagram#17]
dotnet tool install -g CsdlToDiagram

error NU1202: Package CsdlToDiagram 0.14.1 is not compatible with net5.0 (.NETCoreApp,Version=v5.0) / any. Package CsdlToDiagram 0.14.1 supports: net6.0 (.NETCoreApp,Version=v6.0) / any
The tool package could not be restored.
Tool 'csdltodiagram' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool

**Comment by gareth-a-jones** [comment]
Pushed a new multitargetting version for 5.0 and 6.0 in #18 
This is 0.14.2 on nuget.
